### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by polosskevin** [polosskevin/zia#47]
- [x] intégration moduleLoader
- [x] intégration pipeline de module (vincent)
- [x] processing request
- [x] action in function of header
- [x] monter en charge
- [x] ajout de modules
- [x] coverall (kevin)
- [x] intégration file watcher (vincent)
- [x] intégration parser (kevin)
